spring:
 datasource:
  name: fangdh  #????
  url: jdbc:mysql://localhost:3306/fangdh #url
  username: root  #???
  password: F750331510  #??
  driver-class-name: com.mysql.jdbc.Driver  #???????
server:
 servlet:
  context-path: /fangdh
 port: 8080